server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    
# 이메일 전송 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: indiefliker@gmail.com
    password: scvfdnsdqlavzjxj
    properties:   
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      schema-locations:
        - classpath:db/table.sql
      data-locations:
        - classpath:db/data.sql
  h2:
    console:
      enabled: true
    output:
      ansi:
      enabled: always

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations:
    - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com.tenco.indiepicter: debug
    
tenco:
  key: 150A0D3EC31A459C6171663BD0990CD382C471DF8F4D19C2C5E6EF3C40D40E37

imp:
  api-key: 5064237412678407
  secret-key: k4MtJ9y69ErPEGGhWQdE41KIFktLgp9uzgGXE8XMVUL0F4kZKzmCE7p8fsv0G8L2UDs5iLW3LYXdNUrE
  
#Restart 비활성화
  spring:
    devtools:
      restart:
        enabled: false
